In [4]:
import pandas as pd

In [5]:
fpt = pd.read_csv(r"D:\fpt-stock-forecasting\data\raw\fpt_stock_price.csv")

In [6]:
fpt

,time,open,high,low,close,volume,symbol,source,collected_date
0,2009-03-31,2.53,2.58,2.52,2.57,828860,FPT,VCI,2026-06-09
1,2009-04-01,2.68,2.70,2.63,2.70,311150,FPT,VCI,2026-06-09
2,2009-04-02,2.83,2.83,2.79,2.83,1114300,FPT,VCI,2026-06-09
3,2009-04-03,2.95,2.95,2.95,2.95,900770,FPT,VCI,2026-06-09
4,2009-04-07,2.95,3.09,2.92,3.09,1551610,FPT,VCI,2026-06-09
...,...,...,...,...,...,...,...,...,...
4289,2026-06-08,73.70,74.50,72.80,72.90,10952915,FPT,VCI,2026-06-15
4290,2026-06-09,73.40,74.20,72.60,73.70,7803771,FPT,VCI,2026-06-15
4291,2026-06-10,73.50,74.50,73.50,74.20,4736000,FPT,VCI,2026-06-15
4292,2026-06-11,73.90,73.90,73.10,73.10,3507300,FPT,VCI,2026-06-15
4293,2026-06-12,73.60,74.30,73.50,73.50,5688200,FPT,VCI,2026-06-15

In [7]:
#sửa dataset fpt chỉ lấy từ 1/1/2010 trở đi
fpt = fpt[fpt["time"] >= "2010-01-01"]
fpt

,time,open,high,low,close,volume,symbol,source,collected_date
194,2010-01-04,4.80,4.89,4.69,4.89,235620,FPT,VCI,2026-06-09
195,2010-01-05,5.07,5.07,4.89,4.89,200040,FPT,VCI,2026-06-09
196,2010-01-06,4.89,4.95,4.71,4.80,94870,FPT,VCI,2026-06-09
197,2010-01-07,4.80,4.83,4.74,4.77,102720,FPT,VCI,2026-06-09
198,2010-01-08,4.86,4.86,4.63,4.63,161560,FPT,VCI,2026-06-09
...,...,...,...,...,...,...,...,...,...
4289,2026-06-08,73.70,74.50,72.80,72.90,10952915,FPT,VCI,2026-06-15
4290,2026-06-09,73.40,74.20,72.60,73.70,7803771,FPT,VCI,2026-06-15
4291,2026-06-10,73.50,74.50,73.50,74.20,4736000,FPT,VCI,2026-06-15
4292,2026-06-11,73.90,73.90,73.10,73.10,3507300,FPT,VCI,2026-06-15
4293,2026-06-12,73.60,74.30,73.50,73.50,5688200,FPT,VCI,2026-06-15

In [8]:
vnindex = pd.read_csv(r"D:\fpt-stock-forecasting\data\raw\vnindex_price.csv")

In [9]:
vnindex

,time,open,high,low,close,volume,symbol,source,collected_date
0,2009-04-01,282.10,289.50,282.10,289.50,19997530,VNINDEX,VCI,2026-06-06
1,2009-04-02,294.00,297.30,292.40,297.30,28572200,VNINDEX,VCI,2026-06-06
2,2009-04-03,306.60,310.30,306.60,310.30,38327280,VNINDEX,VCI,2026-06-06
3,2009-04-07,313.70,322.40,309.80,322.40,41795600,VNINDEX,VCI,2026-06-06
4,2009-04-08,316.70,328.50,313.40,313.80,54502480,VNINDEX,VCI,2026-06-06
...,...,...,...,...,...,...,...,...,...
4287,2026-06-08,1822.10,1822.95,1789.31,1790.53,714568751,VNINDEX,VCI,2026-06-15
4288,2026-06-09,1799.21,1800.80,1780.71,1793.05,527110166,VNINDEX,VCI,2026-06-15
4289,2026-06-10,1793.45,1805.03,1789.48,1803.71,625012446,VNINDEX,VCI,2026-06-15
4290,2026-06-11,1793.15,1801.99,1788.64,1798.61,410733903,VNINDEX,VCI,2026-06-15
4291,2026-06-12,1813.07,1813.57,1788.56,1791.65,640199320,VNINDEX,VCI,2026-06-15

In [10]:
vnindex = vnindex[vnindex["time"] >= "2010-01-01"]
vnindex

,time,open,high,low,close,volume,symbol,source,collected_date
192,2010-01-04,501.70,517.10,501.70,517.10,42051600,VNINDEX,VCI,2026-06-06
193,2010-01-05,538.80,539.40,530.20,532.50,66619450,VNINDEX,VCI,2026-06-06
194,2010-01-06,527.40,538.80,526.40,534.50,64222280,VNINDEX,VCI,2026-06-06
195,2010-01-07,536.80,540.80,530.70,533.30,66287110,VNINDEX,VCI,2026-06-06
196,2010-01-08,541.00,544.50,520.90,520.90,76177100,VNINDEX,VCI,2026-06-06
...,...,...,...,...,...,...,...,...,...
4287,2026-06-08,1822.10,1822.95,1789.31,1790.53,714568751,VNINDEX,VCI,2026-06-15
4288,2026-06-09,1799.21,1800.80,1780.71,1793.05,527110166,VNINDEX,VCI,2026-06-15
4289,2026-06-10,1793.45,1805.03,1789.48,1803.71,625012446,VNINDEX,VCI,2026-06-15
4290,2026-06-11,1793.15,1801.99,1788.64,1798.61,410733903,VNINDEX,VCI,2026-06-15
4291,2026-06-12,1813.07,1813.57,1788.56,1791.65,640199320,VNINDEX,VCI,2026-06-15

In [11]:
import sys
import os

In [12]:
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))

In [13]:
if project_root not in sys.path:
    sys.path.append(project_root)

In [14]:
print(fpt.describe())

              open         high          low        close        volume
count  4100.000000  4100.000000  4100.000000  4100.000000  4.100000e+03
mean     29.979393    30.305585    29.659361    29.969980  1.899580e+06
std      33.203358    33.557392    32.838527    33.180801  2.991696e+06
min       3.340000     3.510000     3.340000     3.490000  0.000000e+00
25%       6.410000     6.525000     6.315000     6.440000  3.415825e+05
50%      13.420000    13.520000    13.250000    13.390000  9.385370e+05
75%      48.060000    48.450000    47.600000    47.960000  2.106322e+06
max     129.710000   131.310000   129.120000   129.880000  4.784075e+07

In [15]:
print(vnindex.describe())

              open         high          low        close        volume
count  4100.000000  4100.000000  4100.000000  4100.000000  4.100000e+03
mean    878.628815   884.199905   872.094861   878.382856  3.192777e+08
std     378.565645   380.918609   374.911799   378.185501  3.391127e+08
min     334.930000   339.320000   332.280000   336.730000  0.000000e+00
25%     536.182500   540.575000   531.252500   536.280000  7.966796e+07
50%     862.065000   868.135000   857.675000   862.210000  1.520727e+08
75%    1174.847500  1182.290000  1166.485000  1173.962500  5.385043e+08
max    1933.010000  1933.110000  1909.690000  1927.940000  2.698902e+09

In [ ]:
merge_df = pd.read_csv(r"D:\fpt-stock-forecasting\data\processed\merged_dataset.csv")
merge_df

,time,open,high,low,close,volume,vnindex_close,return_1d,log_return_1d,ma5,...,volatility_20d,high_low_pct,open_close_pct,atr14,bollinger_width20,vnindex_return_1d,vnindex_ma20,vnindex_close_ma20_ratio,vnindex_volatility_20d,target_next_close
0,2010-02-01,4.54,4.69,4.54,4.63,122980,487.00,0.013129,0.013044,4.652,...,0.019079,0.032397,0.019824,0.117143,0.082454,0.010373,500.2500,-0.026487,0.019786,4.80
1,2010-02-02,4.74,4.80,4.71,4.80,401340,487.90,0.036717,0.036059,4.652,...,0.021007,0.018750,0.012658,0.114286,0.073998,0.001848,498.0200,-0.020320,0.018295,5.01
2,2010-02-03,4.95,5.01,4.86,5.01,688030,495.50,0.043750,0.042820,4.728,...,0.022776,0.029940,0.012121,0.121429,0.097375,0.015577,496.0700,-0.001149,0.018751,5.01
3,2010-02-04,4.98,5.04,4.95,5.01,417620,503.80,0.000000,0.000000,4.804,...,0.022694,0.017964,0.006024,0.121429,0.116322,0.016751,494.5950,0.018611,0.019297,4.80
4,2010-02-05,4.95,4.98,4.77,4.80,252750,493.00,-0.041916,-0.042820,4.850,...,0.023776,0.043750,-0.030303,0.132143,0.118131,-0.021437,493.2000,-0.000406,0.019199,4.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4074,2026-06-05,76.00,76.00,74.30,75.00,11249802,1838.90,-0.014455,-0.014560,75.060,...,0.021702,0.022667,-0.013158,2.232857,0.121950,0.004013,1880.1210,-0.021925,0.006731,72.90
4075,2026-06-08,73.70,74.50,72.80,72.90,10952915,1790.53,-0.028000,-0.028399,75.060,...,0.021821,0.023320,-0.010855,2.284286,0.109679,-0.026304,1874.8725,-0.044986,0.008486,73.70
4076,2026-06-09,73.40,74.20,72.60,73.70,7803771,1793.05,0.010974,0.010914,74.840,...,0.021861,0.021710,0.004087,1.997143,0.098450,0.001407,1869.4700,-0.040878,0.008438,74.20
4077,2026-06-10,73.50,74.50,73.50,74.20,4736000,1803.71,0.006784,0.006761,74.380,...,0.021873,0.013477,0.009524,1.913571,0.085289,0.005945,1864.7370,-0.032727,0.008663,73.10
4078,2026-06-11,73.90,73.90,73.10,73.10,3507300,1798.61,-0.014825,-0.014936,73.780,...,0.019854,0.010944,-0.010825,1.816429,0.084971,-0.002828,1858.3945,-0.032170,0.007710,73.50

: